### ISSUE TITLE
Instructions for running on Tweebank v2

### ISSUE THREAD

**Issue by neutralino** [Oneplus/twpipe#1]
Hi, I'm trying to re-train your system over the [Tweebank v2 datasets](https://github.com/Oneplus/Tweebank).  Is there a set of instructions for the right way to do so?  Can the datasets be fed in directly? I was able to build the code, but am getting an illegal conllu error:
```
$ ./bin/twpipe --train /Users/<username>/Tweebank/en-ud-tweet-train.conllu
[dynet] random seed: 2040050511
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
2018-07-04 21:39:46 [info] [embedding] loaded embedding 3 entries.
2018-07-04 21:39:46 [info] [cluster] loaded cluster 3 entries.
2018-07-04 21:39:46 [info] [corpus] reading training data from: /Users/<username>/Tweebank/en-ud-tweet-train.conllu 
Assertion failed: ((tokens.size() > 6)&&("[corpus] illegal conllu format, number of column less than 6.")), function parse_data, file /Users/<username>/twpipe/src/twpipe/corpus.cc, line 266.
[1]    5498 abort      ./bin/twpipe --train /Users/<username>/Tweebank/en-ud-tweet-train.conllu
```
It looks like it's complaining about the commented lines `# tweet_id = feb_jul_16.1463316480` in the dataset.  I suspect I'm missing other inputs (e.g. embedding files) at this point as well.

Thanks for any help.
(Alternatively, if you have a pre-trained model that could be shared, that would be great as well.)

**Comment by neutralino** [comment]
I was able to get past this and train the models by just removing the tweet_id lines.  I also should have just run
```
$ ./bin/twpipe --help
```
(which is quite detailed) to figure out what other inputs are needed.

**Comment by Oneplus** [comment]
Hi, I've updated the readme and code. It should work with the `en-ud-tweebank.train.conllu`.

**Comment by neutralino** [comment]
Thank you!
